//jshint esversion:6

const express = require("express");
const bodyParser = require("body-parser");
const ejs = require("ejs");
const _ = require("lodash");
const welcomeTitle = "WebApp Axcora";
const welcomeDesc = "Pembuatan website , aplikasi kasir toko,aplikasi restoran cafe ,aplikasi sekolah , dan aplikasi android app bundle.";
const welcomeButton1 = "Get Start →";
const welcomeUrlButton1 = "#start";
const welcomeCover1 = "/img/pembuatan aplikasi android (22).jpeg";
const welcomeCover2 = "/img/pembuatan aplikasi android (14).jpeg";
const welcomeCover3 = "/img/apksekolah.jpeg";
const welcomeCover4 = "/img/pembuatan aplikasi android (53).jpeg";
const welcomeCover5 = "/img/pembuatan aplikasi android (3).jpeg";
const welcomeCover6 = "/img/pembuatan aplikasi android (10).jpeg";
const welcomeCover7 = "/img/pembuatan aplikasi android (33).jpeg";
const welcomeBanner1 = "/img/aplikasi rumah makan cafe restoran website online shgop (5).jpeg";
const welcomeBanner2 = "/img/aplikasi toko kasir online shop (1).jpg";
const welcomeBanner3 = "/img/rumah makan cafe restoran.jpg";
const welcomeBanner4 = "/img/aplikasi kasir toko online shop (10).png";
const welcomeSection1Title = "About Axcora Developer";
const welcomeSection1Desc = "Awesome Technology";
const welcomeSection1Text = "Dukungan penuh technology terbaik";
const welcomeSection1Icon1 = "fab fa-angular";
const welcomeSection1Icon2 = "fab fa-node-js";
const welcomeSection1Icon3 = "fab fa-react";
const welcomeSection1Icon4 = "fab fa-laravel";
const welcomeSection1Icon5 = "fab fa-symfony";
const welcomeSection1Icon6 = "fab fa-python";
const welcomeSection1Icon7 = "fab fa-sketch";
const welcomeSection1Icon8 = "fab fa-github";
const welcomeSection1Content = "Axcora technology adalah sebuah solusi untuk kebutuhan website dan aplikasi mu, dengan konsep modern web app integrasi website dan aplikasi online dalam satu apps memudahkan dalam berbagai kebutuhan untuk bekerja dengan cepat, selain itu tentunya akan menghemat budget anggaran belanja dalam kebutuhan technology informasi untuk aplikasi pembukuan serperti invoice penjualan kasir untuk toko minimarket , restoran cafe , inventori stok management system hingga kebutuhan untuk pembukuan dengan laporan detail, dan tentunya untuk edukasi sekolah hadir dengan aplikasi yang membantu dalam proses belajar mengajar dan pembukuan sekolah. ";
const welcomeSection1Service = "Layanan Kami";
const welcomeSection1Services = "Pembuatan website dan aplikasi invoice, akuntansi, kasir, sekolah apps, aplikasi android informasi company profile perusahaan , toko shop store outlet, restoran cafe rumah makan kuliner, sekolah edukasi , dan berbagai bidang inustri bisnis lain nya";
const welcomeSpace1 = "fab fa-studiovinari";
const welcomeSpace2 = "fab fa-buromobelexperte";
const welcomeSpace3 = "fab fa-android";
const welcomeSpace1Title = "Web";
const welcomeSpace2Title = "App";
const welcomeSpace3Title = "APK";
const welcomeSpace1desc = "Kembangkan project website modern bersama kami dengan technology terbaru untuk develope modern situs mu.";
const welcomeSpace2desc = "Percayakan aplikasi online cloud web app dengan axcora untuk kebutuhan terbaik dalam pembukuan bisnis.";
const welcomeSpace3desc = "Sentuh dan lebih dekat dengan pelanggan via aplikasi android untuk memberikan informasi usaha mu.";
const welcomeImg = "https://1.bp.blogspot.com/-6B-s5iMYeNw/YQ16KQUwxcI/AAAAAAAAQMc/T2nmdoYWIP0vJiTEEr3EFGuuQxtx67EsACLcBGAsYHQ/s729/online.png";
const welcomeIlus1 ="/img/homs.png";
const welcomeIlus2 ="/img/3.png";
const welcomeIlus3 ="/img/1.png";
const welcomeIlus4 ="/img/themesas.png";
const welcomeIlusTitle ="Get Start With Axcora";
const welcomeIlusDesc ="Memulai menggunakan layanan axcora technology web apps.";
const welcomeIlusContent1Title ="Consult";
const welcomeIlusContent1 ="Yap.. konsultasikan terlebih dahulu kebutuhan dan keinginan dalam develope serta delpoy website maupun aplikasi mu.";
const welcomeIlusContent2Title ="Concept";
const welcomeIlusContent2 ="Pembicaraan mengenai konsep untuk kebutuhan bekerja maupun sebagai website informasi untuk digunakan.";
const welcomeIlusContent3Title ="Techno";
const welcomeIlusContent3 ="Selanjutnya akan di sesuaikan dengan technology untuk penggunaan dan pembangunan project website apps.";
const welcomeIlusContent41Title ="Calculation";
const welcomeIlusContent4 ="Memulai berbicara mengenai biaya dan anggaran yang dibutuhkan untuk kebutuhan pembuatan webstite dan applikasi. ";
const welcomeIlusContent5Title ="Develop";
const welcomeIlusContent5 ="Selanjutnya team developer kami akan bekerja sesuai dengan skema konsep yang sudah terapai dan disetujui bersama.";
const welcomeIlusContent6Title ="Deploy";
const welcomeIlusContent6 ="Dan saatnya mulai melakukan konfigurasi dan installasi web app di cloud, dan web app sudah siap digunakan.";
const welcomeSupportTitle ="Tech Support";
const welcomeSupportDesc ="Dukungan Technology terbaik";
const welcomeSupportContent ="Dengan mendapatkan dukungan terbaik technology untuk proses develope dan deploy web app.";
const welcomeSupport1 ="CloudFlare";
const welcomeSupport1Desc ="Security kemananan terbaik dengan SSL script dari cloudflare technology untuk digunakan.";
const welcomeSupport1Icon ="fas fa-shield-alt";
const welcomeSupport2 ="LiteSpeed";
const welcomeSupport2Icon ="fas fa-fighter-jet";
const welcomeSupport2Desc ="Kebutuhan akan stabilitas dan kecapatan via cloud base dengan litespeed web server.";
const welcomeSupport3 ="CMS";
const welcomeSupport3Icon ="fab fa-drupal";
const welcomeSupport3Desc ="Content Management System untuk kebutuhan mengembangkan website dengan kemudahan digunakan.";
const welcomeSupport4 ="Framework";
const welcomeSupport4Icon ="fab fa-laravel";
const welcomeSupport4Desc ="Dukungan Berbagai framework dalam deploy modern web applikasi tersemat.";
const welcomeSupport5 ="Databsased";
const welcomeSupport5Icon ="fas fa-satellite-dish";
const welcomeSupport5Desc ="Menggunakan databases untuk website dan aplikasi dalam pengelolahan data.";
const welcomeSupport6 ="Hosting";
const welcomeSupport6Icon ="fas fa-satellite";
const welcomeSupport6Desc ="Menggunakan cloud hosting dalam implementasi full online technology.";
const welcomeServicaTitle ="Layanan Kami";
const welcomeServica1Title ="Website";
const welcomeServica1Cover ="Pembuatan website modern";
const welcomeServica1Desc ="/img/pembuatan aplikasi android.jpg";
const welcomeServica1Url ="https://axcora.com/getaxcoracms/index.php?id=new-website-template-themes";
const welcomeServica2Title ="Applikasi";
const welcomeServica2Desc ="/img/pembuatan aplikasi android terbaru.jpg";
const welcomeServica2Cover ="Website dan aplikasi terintgrasi";
const welcomeServica2Url ="https://axcora.com/web-app.html";
const welcomeServica3Title ="Android";
const welcomeServica3Desc ="/img/pembuatan website terbaru (1).jpg";
const welcomeServica3Cover ="Pembuatan aplikasi android APP bundle";
const welcomeServica3Url ="https://webdev.axcora.com/services/pembuatanandroid";
const welcomeServica4Title ="School";
const welcomeServica4Desc ="/img/pembuatan website terbaru (1).png";
const welcomeServica4Cover ="Solusi edukasi sekolah dengan axcora school webapp ";
const welcomeServica4Url ="https://school.axcora.com";
const welcomeServica5Title ="Office";
const welcomeServica5Desc ="/img/pembuatan website terbaru (2).png";
const welcomeServica5Cover ="Terbaik untuk office technology";
const welcomeServica5Url ="https://axcora.com/pembuatan-website-company-profile.html";
const welcomeServica6Title ="Shop";
const welcomeServica6Desc ="/img/pembuatan website terbaru (3).png";
const welcomeServica6Cover ="Alternatif dalam technology retail konsep";
const welcomeServica6Url ="https://axcora.com/pembuatan-website-toko-online-shop-store-outlet-apps.html";
const welcomeServica7Title ="Kuliner";
const welcomeServica7Desc ="/img/pembuatan website terbaru (4).png";
const welcomeServica7Cover ="Mudahkan segala nya dengan kuliner web apps.";
const welcomeServica7Url ="https://axcora.com/pembuatan-website-restoran-cafe-rumah-makan-app.html";
const welcomeGalTitle ="Best Seller Services.";
const welcomeGalTitle1 ="Android Bundle Apps";
const welcomeGalTitle2 ="Online Shop + Web App";
const welcomeGalTitle3 ="Complete Resto Web App";
const welcomeGalTitle4 ="School All in one Apps";
const welcomeGalDesc1 ="Pembuatan android premium version murah";
const welcomeGalDesc2 ="Aplikasi toko online shop dan website + aplikasi kasir pos";
const welcomeGalDesc3 ="Website restoran modern integrasi aplikasi restoran pos kasir";
const welcomeGalDesc4 ="All in one aplikasi sekolah super lengkap";
const welcomeGalSpek1 ="/img/24.jpg";
const welcomeGalSpek2 ="/img/Roboshop App - aplikasi toko online shop.jpg";
const welcomeGalSpek3 ="/img/rumah makan cafe restoran.jpg";
const welcomeGalSpek4 ="/img/1.jpg";
const welcomeGalUrl1 ="https://www.youtube.com/watch?v=hvzjFQ7nvoQ";
const welcomeGalUrl2 ="https://www.youtube.com/watch?v=ilxs6l5Dhfw";
const welcomeGalUrl3 ="https://www.youtube.com/watch?v=3eqJz3KqY1M";
const welcomeGalUrl4 ="https://www.youtube.com/watch?v=IK77uOvJ-pU";
const welcomesourceTitle ="Our Lastest Source Code Project";
const welcomesource1 ="Axcora Cashier";
const welcomesource2 ="Axcora E-Learn";
const welcomesource3 ="Get Axcora CMS";
const welcomesourcedesc1 ="A Free and full open source code point of sale web apps technology";
const welcomesourcedesc2 ="E-Learn web app for school - untuk proses belajar mengajar";
const welcomesourcedesc3 ="Content Management System Modern dengan kecepatan dan kemudahan nya";
const welcomesourceImg1 ="https://axcora.com/getaxcoracms/data/uploads/plugins/freepointofsaleapp.png";
const welcomesourceImg2 ="https://1.bp.blogspot.com/-zc50aOG3P44/X8o9ft70npI/AAAAAAAALn0/Xgr_lTO2R2El6ZrfUmpHctngaYqDji81wCLcBGAsYHQ/s1828/aplikasi%2Belarning%2Bsekolah%2Bsd%2Bsmp%2Bsma%2Bonline%2Bgratis%2Bdownload.jpg";
const welcomesourceImg3 ="https://axcora.com/getaxcoracms/data/uploads/screenshot_2020-12-08-get-axcora-cms.jpg";
const welcomesourceUrl1 ="https://axcora.com/getaxcoracms/index.php?id=free-point-of-sale-app-download";
const welcomesourceUrl2 ="https://axcora.com/e-learndownload/";
const welcomesourceUrl3 ="https://axcora.com/getaxcoracms/index.php?id=download-new-cms-modern";
const welcomeft1 = "Need Help ??";
const welcomeft2 = "Just Contact Us...";
const welcomeft3 = "Whatsapp";
const welcomeft4 = "Call";
const welcomeft5 = "https://wa.me/6285646104747";
const welcomeft6 = "tel:+6287819355589";
const app = express();

app.set('view engine', 'ejs');

app.use(bodyParser.urlencoded({extended: true}));
app.use(express.static("public"));

let posts = [];

app.get("/", function(req, res){res.render("welcome", { title: welcomeTitle, desc: welcomeDesc, b1: welcomeButton1, Urlb1: welcomeUrlButton1, cover1: welcomeCover1, cover2: welcomeCover2, cover3: welcomeCover3, cover4: welcomeCover4, cover5: welcomeCover5, cover6: welcomeCover6, cover7: welcomeCover7, banner1: welcomeBanner1, banner2: welcomeBanner2, banner3: welcomeBanner3, banner4: welcomeBanner4, titles1: welcomeSection1Title, descs1: welcomeSection1Desc, texts1: welcomeSection1Text, s1icon1: welcomeSection1Icon1, s1icon2: welcomeSection1Icon2, s1icon3: welcomeSection1Icon3, s1icon4: welcomeSection1Icon4, s1icon5: welcomeSection1Icon5, s1icon6: welcomeSection1Icon6, s1icon7: welcomeSection1Icon7, s1icon8: welcomeSection1Icon8, s1content: welcomeSection1Content, s1service: welcomeSection1Service, s1services: welcomeSection1Services, space1title: welcomeSpace1Title, space2title: welcomeSpace2Title, space3title: welcomeSpace3Title, space1: welcomeSpace1, space1desc: welcomeSpace1desc, space2: welcomeSpace2, space2desc: welcomeSpace2desc, space3: welcomeSpace3, space3desc: welcomeSpace3desc, iTitle: welcomeIlusTitle, iDesc: welcomeIlusDesc, iContent1title: welcomeIlusContent1Title, iContent2title: welcomeIlusContent2Title, iContent3title: welcomeIlusContent3Title, iContent4title: welcomeIlusContent41Title, iContent5title: welcomeIlusContent5Title, iContent6title: welcomeIlusContent6Title, iContent1: welcomeIlusContent1, iContent2: welcomeIlusContent2, iContent3: welcomeIlusContent3, iContent4: welcomeIlusContent4, iContent5: welcomeIlusContent5, iContent6: welcomeIlusContent6, ilus1: welcomeIlus1, ilus2: welcomeIlus2, ilus3: welcomeIlus3, ilus4: welcomeIlus4, img: welcomeImg, supTitle: welcomeSupportTitle, supDesc: welcomeSupportDesc, supContent: welcomeSupportContent, sup1Title: welcomeSupport1, sup1Icon: welcomeSupport1Icon, sup1Content: welcomeSupport1Desc, sup2Title: welcomeSupport2, sup2Icon: welcomeSupport2Icon, sup2Content: welcomeSupport2Desc, sup3Title: welcomeSupport3, sup3Icon: welcomeSupport3Icon, sup3Content: welcomeSupport3Desc, sup4Title: welcomeSupport4, sup4Icon: welcomeSupport4Icon, sup4Content: welcomeSupport4Desc, sup5Title: welcomeSupport5, sup5Icon: welcomeSupport5Icon, sup5Content: welcomeSupport5Desc, sup6Title: welcomeSupport6, sup6Icon: welcomeSupport6Icon, sup6Content: welcomeSupport6Desc, servTitle: welcomeServicaTitle, servTitle1: welcomeServica1Title, servDesc1: welcomeServica1Desc, servCover1: welcomeServica1Cover, servUrl1: welcomeServica1Url, servTitle2: welcomeServica2Title, servDesc2: welcomeServica2Desc, servCover2: welcomeServica2Cover, servUrl2: welcomeServica2Url, servTitle3: welcomeServica3Title, servDesc3: welcomeServica3Desc, servCover3: welcomeServica3Cover, servUrl3: welcomeServica3Url, servTitle4: welcomeServica4Title, servDesc4: welcomeServica4Desc, servCover4: welcomeServica4Cover, servUrl4: welcomeServica4Url, servTitle5: welcomeServica5Title, servDesc5: welcomeServica5Desc, servCover5: welcomeServica5Cover, servUrl5: welcomeServica5Url, servTitle6: welcomeServica6Title, servDesc6: welcomeServica6Desc, servCover6: welcomeServica6Cover, servUrl6: welcomeServica6Url, servTitle7: welcomeServica7Title, servDesc7: welcomeServica7Desc, servCover7: welcomeServica7Cover, servUrl7: welcomeServica7Url, galTitle: welcomeGalTitle, galTitle1: welcomeGalTitle1, galDesc1: welcomeGalDesc1, galSpek1: welcomeGalSpek1, galUrl1: welcomeGalUrl1, galTitle2: welcomeGalTitle2, galDesc2: welcomeGalDesc2, galSpek2: welcomeGalSpek2, galUrl2: welcomeGalUrl2, galTitle3: welcomeGalTitle3, galDesc3: welcomeGalDesc3, galSpek3: welcomeGalSpek3, galUrl3: welcomeGalUrl3, galTitle4: welcomeGalTitle4, galDesc4: welcomeGalDesc4, galSpek4: welcomeGalSpek4, galUrl4: welcomeGalUrl4, sourceTitle: welcomesourceTitle, source1: welcomesource1, source2: welcomesource2, source3: welcomesource3, sourceImg1: welcomesourceImg1, sourceImg2: welcomesourceImg2, sourceImg3: welcomesourceImg3, sourcedesc1: welcomesourcedesc1, sourcedesc2: welcomesourcedesc2, sourcedesc3: welcomesourcedesc3, sourceUrl1: welcomesourceUrl1, sourceUrl2: welcomesourceUrl2, sourceUrl3: welcomesourceUrl3, ft1: welcomeft1, ft2: welcomeft2, ft3: welcomeft3, ft4: welcomeft4, ft5: welcomeft5, ft6: welcomeft6 });});

app.listen(8300, function() {
  console.log("Server started on port 8300 open localhost:8300");
});
